<?php

return [
    'roles' => [
        ['group_id' => 1, 'group_name' => 'Roles', 'name' => 'List Roles', 'slug' => 'roles.index'],
        ['group_id' => 1, 'group_name' => 'Roles', 'name' => 'Create Role', 'slug' => 'roles.store'],
        ['group_id' => 1, 'group_name' => 'Roles', 'name' => 'Show Role', 'slug' => 'roles.show'],
        ['group_id' => 1, 'group_name' => 'Roles', 'name' => 'Update Role', 'slug' => 'roles.update'],
        ['group_id' => 1, 'group_name' => 'Roles', 'name' => 'Delete Role', 'slug' => 'roles.destroy'],
    ],
    'employees' => [
        ['group_id' => 2, 'group_name' => 'Employees', 'name' => 'List Employees', 'slug' => 'employees.index'],
        ['group_id' => 2, 'group_name' => 'Employees', 'name' => 'Create Employee', 'slug' => 'employees.store'],
        ['group_id' => 2, 'group_name' => 'Employees', 'name' => 'Show Employee', 'slug' => 'employees.show'],
        ['group_id' => 2, 'group_name' => 'Employees', 'name' => 'Update Employee', 'slug' => 'employees.update'],
        ['group_id' => 2, 'group_name' => 'Employees', 'name' => 'Delete Employee', 'slug' => 'employees.destroy'],
    ],
    'employee_types' => [
        ['group_id' => 3, 'group_name' => 'Employee Types', 'name' => 'List Employee Types', 'slug' => 'employee-types.index'],
        ['group_id' => 3, 'group_name' => 'Employee Types', 'name' => 'Create Employee Type', 'slug' => 'employee-types.store'],
        ['group_id' => 3, 'group_name' => 'Employee Types', 'name' => 'Show Employee Type', 'slug' => 'employee-types.show'],
        ['group_id' => 3, 'group_name' => 'Employee Types', 'name' => 'Update Employee Type', 'slug' => 'employee-types.update'],
        ['group_id' => 3, 'group_name' => 'Employee Types', 'name' => 'Delete Employee Type', 'slug' => 'employee-types.destroy'],
    ],
    'employee_attendance' => [
        ['group_id' => 4, 'group_name' => 'Employee Attendance', 'name' => 'List Employee Attendance', 'slug' => 'employee-attendance.index'],
        ['group_id' => 4, 'group_name' => 'Employee Attendance', 'name' => 'Create Employee Attendance', 'slug' => 'employee-attendance.store'],
        ['group_id' => 4, 'group_name' => 'Employee Attendance', 'name' => 'Show Employee Attendance', 'slug' => 'employee-attendance.show'],
        ['group_id' => 4, 'group_name' => 'Employee Attendance', 'name' => 'Update Employee Attendance', 'slug' => 'employee-attendance.update'],
        ['group_id' => 4, 'group_name' => 'Employee Attendance', 'name' => 'Delete Employee Attendance', 'slug' => 'employee-attendance.destroy'],
    ],
    'employee_designation' => [
        ['group_id' => 5, 'group_name' => 'Employee Designations', 'name' => 'List Employee Designations', 'slug' => 'employee-designations.index'],
        ['group_id' => 5, 'group_name' => 'Employee Designations', 'name' => 'Create Employee Designation', 'slug' => 'employee-designations.store'],
        ['group_id' => 5, 'group_name' => 'Employee Designations', 'name' => 'Show Employee Designation', 'slug' => 'employee-designations.show'],
        ['group_id' => 5, 'group_name' => 'Employee Designations', 'name' => 'Update Employee Designation', 'slug' => 'employee-designations.update'],
        ['group_id' => 5, 'group_name' => 'Employee Designations', 'name' => 'Delete Employee Designation', 'slug' => 'employee-designations.destroy'],
    ],
    'product-categories' => [
        ['group_id' => 6, 'group_name' => 'Product Categories', 'name' => 'List Product Categories', 'slug' => 'product-categories.index'],
        ['group_id' => 6, 'group_name' => 'Product Categories', 'name' => 'Create Product Categories', 'slug' => 'product-categories.store'],
        ['group_id' => 6, 'group_name' => 'Product Categories', 'name' => 'Show Product Categories', 'slug' => 'product-categories.show'],
        ['group_id' => 6, 'group_name' => 'Product Categories', 'name' => 'Update Product Categories', 'slug' => 'product-categories.update'],
        ['group_id' => 6, 'group_name' => 'Product Categories', 'name' => 'Delete Product Categories', 'slug' => 'product-categories.destroy'],
    ],
    'product-varieties' => [
        ['group_id' => 7, 'group_name' => 'Product Variety', 'name' => 'List Product Variety', 'slug' => 'product-varieties.index'],
        ['group_id' => 7, 'group_name' => 'Product Variety', 'name' => 'Create Product Variety', 'slug' => 'product-varieties.store'],
        ['group_id' => 7, 'group_name' => 'Product Variety', 'name' => 'Show Product Variety', 'slug' => 'product-varieties.show'],
        ['group_id' => 7, 'group_name' => 'Product Variety', 'name' => 'Update Product Variety', 'slug' => 'product-varieties.update'],
        ['group_id' => 7, 'group_name' => 'Product Variety', 'name' => 'Delete Product Variety', 'slug' => 'product-varieties.destroy'],
    ],
    'products' => [
        ['group_id' => 8, 'group_name' => 'Product', 'name' => 'List Product', 'slug' => 'products.index'],
        ['group_id' => 8, 'group_name' => 'Product', 'name' => 'Create Product', 'slug' => 'products.store'],
        ['group_id' => 8, 'group_name' => 'Product', 'name' => 'Show Product', 'slug' => 'products.show'],
        ['group_id' => 8, 'group_name' => 'Product', 'name' => 'Update Product', 'slug' => 'products.update'],
        ['group_id' => 8, 'group_name' => 'Product', 'name' => 'Delete Product', 'slug' => 'products.destroy'],
    ],
    'product-announcements' => [
        ['group_id' => 9, 'group_name' => 'Product Announcement', 'name' => 'List Product Announcement', 'slug' => 'product-announcements.index'],
        ['group_id' => 9, 'group_name' => 'Product Announcement', 'name' => 'Create Product Announcement', 'slug' => 'product-announcements.store'],
        ['group_id' => 9, 'group_name' => 'Product Announcement', 'name' => 'Show Product Announcement', 'slug' => 'product-announcements.show'],
        ['group_id' => 9, 'group_name' => 'Product Announcement', 'name' => 'Update Product Announcement', 'slug' => 'product-announcements.update'],
        ['group_id' => 9, 'group_name' => 'Product Announcement', 'name' => 'Delete Product Announcement', 'slug' => 'product-announcements.destroy'],
    ],
    'product-recipes' => [
        ['group_id' => 10, 'group_name' => 'Product Recipe', 'name' => 'List Product Recipe', 'slug' => 'product-recipes.index'],
        ['group_id' => 10, 'group_name' => 'Product Recipe', 'name' => 'Create Product Recipe', 'slug' => 'product-recipes.store'],
        ['group_id' => 10, 'group_name' => 'Product Recipe', 'name' => 'Show Product Recipe', 'slug' => 'product-recipes.show'],
        ['group_id' => 10, 'group_name' => 'Product Recipe', 'name' => 'Update Product Recipe', 'slug' => 'product-recipes.update'],
        ['group_id' => 10, 'group_name' => 'Product Recipe', 'name' => 'Delete Product Recipe', 'slug' => 'product-recipes.destroy'],
    ],
    'grocery-categories' => [
        ['group_id' => 11, 'group_name' => 'Grocery Categories', 'name' => 'List Grocery Category', 'slug' => 'grocery-categories.index'],
        ['group_id' => 11, 'group_name' => 'Grocery Categories', 'name' => 'Create Grocery Category', 'slug' => 'grocery-categories.store'],
        ['group_id' => 11, 'group_name' => 'Grocery Categories', 'name' => 'Show Grocery Category', 'slug' => 'grocery-categories.show'],
        ['group_id' => 11, 'group_name' => 'Grocery Categories', 'name' => 'Update Grocery Category', 'slug' => 'grocery-categories.update'],
        ['group_id' => 11, 'group_name' => 'Grocery Categories', 'name' => 'Delete Grocery Category', 'slug' => 'grocery-categories.destroy'],
    ],
    'grocery-units' => [
        ['group_id' => 12, 'group_name' => 'Grocery Unit', 'name' => 'List Grocery Unit', 'slug' => 'grocery-units.index'],
        ['group_id' => 12, 'group_name' => 'Grocery Unit', 'name' => 'Create Grocery Unit', 'slug' => 'grocery-units.store'],
        ['group_id' => 12, 'group_name' => 'Grocery Unit', 'name' => 'Show Grocery Unit', 'slug' => 'grocery-units.show'],
        ['group_id' => 12, 'group_name' => 'Grocery Unit', 'name' => 'Update Grocery Unit', 'slug' => 'grocery-units.update'],
        ['group_id' => 12, 'group_name' => 'Grocery Unit', 'name' => 'Delete Grocery Unit', 'slug' => 'grocery-units.destroy'],
    ],
    'grocery-purchase-items' => [
        ['group_id' => 13, 'group_name' => 'Grocery Purchase Item', 'name' => 'List Grocery Purchase Item', 'slug' => 'grocery-purchase-items.index'],
        ['group_id' => 13, 'group_name' => 'Grocery Purchase Item', 'name' => 'Create Grocery Purchase Item', 'slug' => 'grocery-purchase-items.store'],
        ['group_id' => 13, 'group_name' => 'Grocery Purchase Item', 'name' => 'Show Grocery Purchase Item', 'slug' => 'grocery-purchase-items.show'],
        ['group_id' => 13, 'group_name' => 'Grocery Purchase Item', 'name' => 'Update Grocery Purchase Item', 'slug' => 'grocery-purchase-items.update'],
        ['group_id' => 13, 'group_name' => 'Grocery Purchase Item', 'name' => 'Delete Grocery Purchase Item', 'slug' => 'grocery-purchase-items.destroy'],
    ],
    'grocery-purchases' => [
        ['group_id' => 14, 'group_name' => 'Grocery Purchase', 'name' => 'List Grocery Purchase', 'slug' => 'grocery-purchases.index'],
        ['group_id' => 14, 'group_name' => 'Grocery Purchase', 'name' => 'Create Grocery Purchase', 'slug' => 'grocery-purchases.store'],
        ['group_id' => 14, 'group_name' => 'Grocery Purchase', 'name' => 'Show Grocery Purchase', 'slug' => 'grocery-purchases.show'],
        ['group_id' => 14, 'group_name' => 'Grocery Purchase', 'name' => 'Update Grocery Purchase', 'slug' => 'grocery-purchases.update'],
        ['group_id' => 14, 'group_name' => 'Grocery Purchase', 'name' => 'Delete Grocery Purchase', 'slug' => 'grocery-purchases.destroy'],
    ],
    'groceries' => [
        ['group_id' => 15, 'group_name' => 'Grocery', 'name' => 'List Grocery', 'slug' => 'groceries.index'],
        ['group_id' => 15, 'group_name' => 'Grocery', 'name' => 'Create Grocery', 'slug' => 'groceries.store'],
        ['group_id' => 15, 'group_name' => 'Grocery', 'name' => 'Show Grocery', 'slug' => 'groceries.show'],
        ['group_id' => 15, 'group_name' => 'Grocery', 'name' => 'Update Grocery', 'slug' => 'groceries.update'],
        ['group_id' => 15, 'group_name' => 'Grocery', 'name' => 'Delete Grocery', 'slug' => 'groceries.destroy'],
    ],
];